# Generated by Django 3.1.7 on 2021-06-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20210607_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contactcategory',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orderrest',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='partnerrestaurant',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='servicetime',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tutorialcategory',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
