# Generated by Django 3.1.7 on 2021-06-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_auto_20210610_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ['food_category']},
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='title',
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='food_category',
            field=models.CharField(default='eService', max_length=200),
        ),
        migrations.AlterField(
            model_name='albumcategory',
            name='album_category',
            field=models.CharField(default='eService', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='blog_category',
            field=models.CharField(default='eService', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='book_category',
            field=models.CharField(default='eService', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientcategory',
            name='client_name',
            field=models.CharField(default='eService', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactcategory',
            name='contact_category',
            field=models.CharField(default='eService', max_length=100),
        ),
        migrations.AlterField(
            model_name='customercategory',
            name='customer_category',
            field=models.CharField(default='eService', max_length=100),
        ),
        migrations.AlterField(
            model_name='division',
            name='title',
            field=models.CharField(default='eService', max_length=128),
        ),
        migrations.AlterField(
            model_name='employeecategory',
            name='employee_category',
            field=models.CharField(default='eService', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordercatgory',
            name='catname',
            field=models.CharField(default='eService', max_length=64),
        ),
        migrations.AlterField(
            model_name='restaurantcategory',
            name='restaurant_category',
            field=models.CharField(default='eService', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='task_category',
            field=models.CharField(default='eService', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorialcategory',
            name='tutorial_category',
            field=models.CharField(default='eService', max_length=100, verbose_name=models.Model),
        ),
    ]
