# Generated by Django 3.1.7 on 2021-06-13 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_auto_20210610_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumlist',
            name='created',
            field=models.DateField(default='2021-06-13'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='created',
            field=models.DateField(default='2021-06-13'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='due_date',
            field=models.DateField(default='2021-06-13'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='scheduled_date',
            field=models.DateField(default='2021-06-13'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.taskcategory'),
        ),
    ]
