# Generated by Django 3.1.7 on 2022-01-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_auto_20210612_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumlist',
            name='created',
            field=models.DateField(default='2022-01-07'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='created',
            field=models.DateField(default='2022-01-07'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='due_date',
            field=models.DateField(default='2022-01-07'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='scheduled_date',
            field=models.DateField(default='2022-01-07'),
        ),
    ]
