# Generated by Django 3.2.10 on 2022-01-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0014_auto_20220107_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumlist',
            name='created',
            field=models.DateField(default='2022-01-08'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='created',
            field=models.DateField(default='2022-01-08'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='due_date',
            field=models.DateField(default='2022-01-08'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='scheduled_date',
            field=models.DateField(default='2022-01-08'),
        ),
    ]
